### ISSUE TITLE
 Hello Zhao Zexing. Can you give me contact information(Email or Wechat)? I need your support for the project MasterFOC in your github. Thank you so much. 

### ISSUE THREAD

**Issue by thietdang** [Zzx-J/MasterFOC#2]

**Comment by Zzx-J** [comment]
Can you be more specific? What kind of support do you need?

**Comment by thietdang** [comment]
I want to control with sensorless mode. have you used sensorless mode on the above project, can you guide me or share me the code.

**Comment by thietdang** [comment]
I'm a new member, thank you very much for sharing your knowledge with me.

**Comment by thietdang** [comment]
This is my email, can i contact you by email for convenience?
"thiet194@gmail.com"

**Comment by Zzx-J** [comment]
Sorry, this repo is just my undergraduate's individual Final Year Project, I only completed and tested the sensored algorithm because of the limited time. I didn't have time to look too deep for sensorless mode. I suggest you look for simpleFOC, which is a powerful FOC library. If you would like to go deeper, VESC maybe another good choice to look at.

**Comment by thietdang** [comment]
With my project, i can control 2 motor with encoder mode and sensorless, i learn more about sensorless control, I need code an SMO estimate the E_Angle of the motor.
Can i ask you a little more? Can i use your algorithm to control 3 phase asynchronous motor like 1 inverter?
